version: '3.8'

services:
  springboot-app:
    image: astar5327/elsa:latest
    platform: linux/amd64
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:log4jdbc:postgresql://localhost:5432/elsa
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: d198050ec738b4fc1736fd70a19194c5ae714c677d0ff1e1a024f6d5edeef30bccea5487c434f3a22f403954cdbad49e5d401fe506803483b46260ce1500939a
      JWT_AT: 3600000
      JWT_RT: 604800000
      OPENAI_API_KEY: sk-proj-Y46RLiFX3AnLBN1nnRXVT3BlbkFJzAHzSK7dKUPreTzWiyFF
      OPENAI_API_URL: https://api.openai.com/v1/chat/completions
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres-db
      - redis
    networks:
      - my-network

  postgres-db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: elsa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
