spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://postgres-db:5432/elsa
    username: postgres
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate-ddl: true
        open-in-view: true
        show-sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

  jwt:
    secret: d198050ec738b4fc1736fd70a19194c5ae714c677d0ff1e1a024f6d5edeef30bccea5487c434f3a22f403954cdbad49e5d401fe506803483b46260ce1500939a
    access-token-validity: 3600000  # 1 hour in milliseconds
    refresh-token-validity: 604800000  # 7 days in milliseconds

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      groups-order: DESC
      operationsSorter: method
      disable-swagger-default-url: true
      display-request-duration: true
      defaultModelsExpandDepth: -1
    api-docs:
      path: /api
      show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    paths-to-match:
      - /**
openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: sk-proj-Y46RLiFX3AnLBN1nnRXVT3BlbkFJzAHzSK7dKUPreTzWiyFF